# Generated by Django 4.2 on 2025-05-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_authorized',
        ),
    ]
